### ISSUE TITLE
base owl carousel styles sheet

### ISSUE THREAD

**Issue by RusinovAnton** [RusinovAnton/generator-scss#1]
``` scss
.owl-carousel {
    position: relative;
    .owl-nav {
        .owl-prev,
        .owl-next {
            position: absolute;
            @include centered-v;
            font-size: 0;
            &.disabled {
                opacity: 0.2;
            }
        }
        .owl-prev {
            left: 0;
            @include triangle-left(20px, 40px, $green);
        }
        .owl-next {
            right: 0;
            @include triangle-right(20px, 40px, $green);
        }
        @media ($min-lg) {
            .owl-prev {
                left: -30px;
            }
            .owl-next {
                right: -30px;
            }
        }
    }
}
```
