### ISSUE TITLE
breakpoints.scss

### ISSUE THREAD

**Issue by RusinovAnton** [RusinovAnton/generator-scss#2]
``` scss
$bp-xl: 1600;
$bp-lg: 1200;
$bp-md: 992;
$bp-sm: 768;
$bp-xs: 580;

$min-xl: 'min-width: #{$bp-xl}px';
$max-xl: 'max-width: #{$bp-xl - 1}px';

$min-lg: 'min-width: #{$bp-lg}px';
$max-lg: 'max-width: #{$bp-lg - 1}px';

$min-md: 'min-width: #{$bp-md}px';
$max-md: 'max-width: #{$bp-md - 1}px';

$min-sm: 'min-width: #{$bp-sm}px';
$max-sm: 'max-width: #{$bp-sm - 1}px';

$min-xs: 'min-width: #{$bp-xs}px';
$max-xs: 'max-width: #{$bp-xs - 1}px';

```
